config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users
  root to: 'books#index'
  post 'books/:id/unbook', to: 'books#unbook', as: 'unbook' 
  post 'books/:id/book', to: 'books#book', as: 'book_book'
  post 'books/:id/pay', to: 'books#pay', as: 'pay_book'
  get 'home/:id/profile', to: 'home#profile', as: 'profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  enum status: { free: 0 , booked: 1, paid: 2 }
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy book pay unbook]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def book
    @book.status = 1
    @book.user = current_user
    respond_to do |format|  
      if @book.save
        format.js { }
      else
        format.html { render @book, alert: "#{@book.title} is #{@book.status}"}
      end
    end
  end

  def unbook
    sleep 2
    @book.status = 0
    @book.user = nil
    respond_to do |format|  
      if @book.save
        format.js { }
      else
        format.html { render @book, alert: "#{@book.title} is #{@book.status}"}
      end
    end
  end


  def pay
    @book.status = 2
    respond_to do |format|  
      if @book.save
        format.html { redirect_to @book, notice: "#{@book.title} was successfully paid"}
      else
        format.html { render @book, alert: "#{@book.title} is #{@book.status}"}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def profile
    @user = current_user
    @books = Book.where(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/_show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>

<% if @user %>
  <p>
    <strong>User:</strong>
    <%= @book.user.email %>
  </p>
<% end %>

<%= button_to 'Desreservar', unbook_path(@book), remote: true %>
<%= button_to 'Pay', pay_book_path(@book), class:"pay" %>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/book.js.erb
function displayTimer (miliseconds) {
  let end = miliseconds / 1000 ;
  let min = $("#minutes")[0];
  let sec = $("#seconds")[0];
  if (end > 0 ) {
    let ticker = setInterval( function (){
    end--;
    if (end <= 0 ) { 
      clearInterval(ticker); 
      disablePay(); }
    let secs = end;
    let mins = Math.floor(secs / 60 ); // 1 min = 60 secs
    secs -= mins * 60 ;
    min.innerHTML = ( "00" + mins).slice( -2 );
    sec.innerHTML = ( "00" + secs).slice( -2 );
    }, 1000);
  }
}

function disablePay() {
  $(".pay").prop('disabled', true);
  $.ajax({
    url: "<%= unbook_path(@book) %>", 
    type: "POST",
    dataType: 'script',
    data: { book: "<%= @book %>"}
  });
};

displayTimer(120000)
$("#show").html("<%= escape_javascript ( render partial: 'show')%>")

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<div id="show", data-url="#{unbook_path(@book)}"></div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
        <td><%= button_to 'Reservar', book_book_path(book), remote: true %></td>
        <td><%= link_to 'Show', book, remote: true %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.js.erb
$("#show").html("<%= escape_javascript ( render partial: 'show')%>")

app/views/books/unbook.js.erb
$("#show").html("<%= escape_javascript ( render partial: 'show')%>")

app/views/home/profile.html.erb
<h3 class="mb-3">
  <strong>Email:</strong>
  <%= @user.email %>
</h3>

<h3 class="mb-3">
  <strong>Booked books:</strong>
</h3>

<ul>
  <% @books.each do |book| %>
  <li>
    <p>
    <strong>Title: </strong><%= book.title %>
    <span><strong>Status: </strong><%= book.status %><span>
    </p>
  </li>
  <% end %>
</ul>

<%= link_to 'Back', root_path, class: "btn btn-dark" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>

  <div>
    <p> Tiempo para pagar: <span id="minutes"></span>: <span id="seconds"></span></p>
  </div>



  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Profile", profile_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Books", books_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sesion
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Sign in", new_user_session_path, class:"dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Sing out", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class:"dropdown-item" %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>